function [b,a] = calcBPFCoeffs(fc,fs,Q)
    wc    = 2*pi*fc/fs;
    alpha = sin(wc)/(2*Q);
    coswc = cos(wc);

    b = [ Q*alpha,...
          0,...
         -Q*alpha];

    a = [1+alpha,...
         -2*coswc,...
         1-alpha];
end